Fix getting signed key and validation function
The current example with hapi-auth-jwt2@8.6.0 results in the following errors
1. Undefined key 
> TypeError: Cannot destructure property `key` of 'undefined' or 'null' at /node_modules/hapi-auth-jwt2/lib/index.js:66
Because the method `jwkRsa.hapiJwt2Key` uses a callback to return the signed key. The async version will return the key as expected.

2. The name of the validation function has changed from `validateFunc` to `validate` see. https://github.com/dwyl/hapi-auth-jwt2/blob/master/test/complete_token.test.js#L22